# Generated by Django 4.1.1 on 2022-09-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='review1',
            new_name='movie1',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie1',
            new_name='review',
        ),
    ]
