# Generated by Django 4.1.1 on 2022-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_rename_movie1_movie_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.TextField(max_length=10),
        ),
    ]
