# Generated by Django 4.1.1 on 2022-09-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movies',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review',
        ),
    ]
